### ISSUE TITLE
Matplotlib version when installing in a clean conda

### ISSUE THREAD

**Issue by GeorgeAlehandro** [aristoteleo/dynamo-release#480]
- [X] I am sure this issue is not simply a general python programming problem
      (if so, please google the answers).
- [X] I have searched github issues and confirm this issue has not reported previously.
- [X] I have confirmed this bug is not related to dynamo version and it exists on the latest version of dynamo.

---

**If this is a question and not a bug report or enhancement request, please post to our Github Discussions channel at [https://github.com/aristoteleo/dynamo-release/discussions](https://github.com/aristoteleo/dynamo-release/discussions)**
Hello, thank you for the package.
**Describe the bug**
Due to an installation of the version of matplotlib version 3.7.1, importing Dynamo will throw an error.
AttributeError: module 'matplotlib.axes' has no attribute '_subplots'
To fix this bug I ended up installing an earlier version of matplotlib like 3.5.3
Would be nice to have dynamo de-leveling the package as the standard 3.7.1 doesn't work in this case but still satisfying the >=3.5.x that dynamo asks for. (maybe add <3.7x? I didn't test if 3.6.x will work).
**To Reproduce**
```
The code that produced the bug:
conda create -n dynamo-python-3.8 python=3.8
conda activate dynamo-python-3.8
pip install dynamo-release
```
Now try this code in python #will throw the error
```
import dynamo 
```
Leave python and type the following on terminal
```
pip install matplotlib==3.5.3
```
Use python again this will work
```
import dynamo 
```
**Post the error message from the Tracebook output:**
AttributeError: module 'matplotlib.axes' has no attribute '_subplots'

**Screenshots**
![image](https://user-images.githubusercontent.com/74742818/233388595-7b6c08ed-6a51-4b45-b0fc-92d07aab973b.png)

**Additional context**
Also there is a bug when working on python version 3.9 and if the installed pandas version is 2.0.0 while running recipe monocle version, but this I should verify again. The fix was to also de-level to pandas 1.5.x and it worked. (The error is related to a future warning that is being thrown in the older versions of pandas as some modifications were made in version 2.0.0).
